runtime: ruby30
env: standard
entrypoint: bundle exec rails s --port $PORT
service: rails
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1
env_variables:
  RAILS_ENV: production
  SECRET_KEY_BASE: 3eed5bc2de5ecc4c3b790746437df70a0a27fd80417f363c8b578ea9108e5fb97b97ef934b15a1988c76412d8b0df3d0a696b0de365999cb27c13061837f5988
  MONGOSRV_URI_PROD: "mongodb+srv://mnizam:nizaminyourarea@cluster0.ns2sz.mongodb.net/nizam_ruby_backend?retryWrites=true&w=majority"
