env: standard
runtime: ruby30
service: rails-promotion-api
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1
env_variables:
  RAILS_ENV: production
